.PHONY: clean All

All:
	@echo "----------Building project:[ heap - Debug ]----------"
	@cd "heap" && "$(MAKE)" -f  "heap.mk"
clean:
	@echo "----------Cleaning project:[ heap - Debug ]----------"
	@cd "heap" && "$(MAKE)" -f  "heap.mk" clean
